version: '3.8'

services:
  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "5001:5001"
    volumes:
      - ./user_service:/app
    networks:
      - rental_network

  car_inventory_service:
    build: ./car_inventory_service
    container_name: car_inventory_service
    ports:
      - "5002:5002"
    volumes:
      - ./car_inventory_service:/app
      - ./car_inventory_service/uploads:/app/uploads
    networks:
      - rental_network

  booking_service:
    build: ./booking_service
    container_name: booking_service
    ports:
      - "5003:5003"
    volumes:
      - ./booking_service:/app
    networks:
      - rental_network

  frontend_service:
    build: ./frontend_service
    container_name: frontend_service
    ports:
      - "5000:5000"
    volumes:
      - ./frontend_service:/app
    networks:
      - rental_network
    depends_on:
      - user_service
      - car_inventory_service
      - booking_service

networks:
  rental_network:
    driver: bridge
